version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
  browser-tools: circleci/browser-tools@1.2.4
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }} 
            - v1-dependencies-
      - run:
          name: Install
          command: |
            npm run install
      - run:
          name: Front Install
          command: |
            npm run front-install
      - run:
          name: Back Install
          command: |
            npm run back-install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }} 

      - run:
          name: Back Build
          command: |
            npm run back-build
      - run:
          name: Front Build
          command: |
            npm run front-build

      - run:
          name: Deploy Back
          command: |
            npm run back-deploy
      - run:
          name: Deploy App
          command: |
            npm run front-deploy

workflows:
  build_deploy:
    jobs:
      - build